BUILD(cmake): Also install man files
mumble-voip/mumble pull request #4473
Opened 2020-09-09 07:04 UTC by Krzmbrzl

On Unix-systems (Linux & Mac) we now also install our man-files when
the user invokes the generated install target.

Fixes #4472

2020-09-09 18:02 UTC, radioactiveman commented
@Krzmbrzl: Thanks for the fast response to my future request. I have tested this patch but it installs the man files to the wrong location. The files must be moved one directory deeper into `man1`. Otherwise they are not found by the man command.

```
thomas ~ $ ls /usr/share/man/
cs        es        hu  jp    man2  man6         nl        pt_BR  sv
da        fr        id  ko    man3  man7         pl        ru     tr
de        fr.UTF-8  it  man0  man4  man8         pl.UTF-8  sl     zh_CN
de.UTF-8  hr        ja  man1  man5  mumble.1.gz  pt        sr     zh_TW
thomas ~ $ man mumble
No manual entry for mumble
thomas ~ $
```

2020-09-10 06:11 UTC, Krzmbrzl commented
Hm too bad. I was kinda hoping that cmake would take care of this when specifying that the file is supposed to be a man file...

Anyways - I think I fixed it now :point_up:

2020-09-10 11:51 UTC, radioactiveman commented
@Krzmbrzl: I found a cleaner way than renaming the man dir in Git. The overlay man file also must be installed in `overlay_gl/CMakeLists.txt`, not `overlay/CMakeLists.txt` which is for Windows.

Please see the patch below. Feel free to adopt it for this pull request if you mention my name in the commit message. Thanks.

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e17cdd6f6..ea2a91730 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -34,6 +34,7 @@ list(APPEND CMAKE_MODULE_PATH
 
 include(pkg-utils)
 include(CTest)
+include(GNUInstallDirs)
 include(project-utils)
 
 
diff --git a/overlay_gl/CMakeLists.txt b/overlay_gl/CMakeLists.txt
index ea86ece62..82f469130 100644
--- a/overlay_gl/CMakeLists.txt
+++ b/overlay_gl/CMakeLists.txt
@@ -116,3 +116,6 @@ else()
 			${LIB_COREFOUNDATION}
 	)
 endif()
+
+# Install Mumble Overlay man file
+install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/../man/mumble-overlay.1" DESTINATION ${CMAKE_INSTALL_MANDIR}/man1 COMPONENT doc)
diff --git a/src/mumble/CMakeLists.txt b/src/mumble/CMakeLists.txt
index bd04edb92..e879635c1 100644
--- a/src/mumble/CMakeLists.txt
+++ b/src/mumble/CMakeLists.txt
@@ -305,6 +305,9 @@ else()
 	else()
 		install(TARGETS mumble BUNDLE DESTINATION . COMPONENT mumble_client)
 	endif()
+
+	# Install Mumble man file
+	install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/../../man/mumble.1" DESTINATION ${CMAKE_INSTALL_MANDIR}/man1 COMPONENT doc)
 endif()
 
 target_compile_definitions(mumble
diff --git a/src/murmur/CMakeLists.txt b/src/murmur/CMakeLists.txt
index 21e1a37fc..77e535ac7 100644
--- a/src/murmur/CMakeLists.txt
+++ b/src/murmur/CMakeLists.txt
@@ -312,4 +312,8 @@ if(WIN32)
 	install(TARGETS murmur RUNTIME DESTINATION . COMPONENT mumble_server)
 else()
 	install(TARGETS murmur RUNTIME DESTINATION bin COMPONENT mumble_server)
+
+	# Install Murmur man files
+	install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/../../man/murmurd.1" DESTINATION ${CMAKE_INSTALL_MANDIR}/man1 COMPONENT doc)
+	install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/../../man/murmur-user-wrapper.1" DESTINATION ${CMAKE_INSTALL_MANDIR}/man1 COMPONENT doc)
 endif()

```

2020-09-10 18:51 UTC, davidebeatrici requested changes
`CMAKE_SOURCE_DIR` evaluates to the path to the directory the root `CMakeLists.txt` is in,

2020-09-10 18:51 UTC, davidebeatrici commented on overlay/CMakeLists.txt
> +	install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../../man1/" TYPE MAN FILES_MATCHING PATTERN "mumble-overlay.1")
```suggestion
	install(DIRECTORY "${CMAKE_SOURCE_DIR}/man.1/" TYPE MAN FILES_MATCHING PATTERN "mumble-overlay.1")
```

2020-09-10 18:51 UTC, davidebeatrici commented on src/mumble/CMakeLists.txt
> +	install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../../man1/" TYPE MAN FILES_MATCHING PATTERN "mumble.1")
```suggestion
	install(DIRECTORY "${CMAKE_SOURCE_DIR}/man.1/" TYPE MAN FILES_MATCHING PATTERN "mumble.1")
```

2020-09-10 18:51 UTC, davidebeatrici commented on src/murmur/CMakeLists.txt
> +	install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../../man1/" TYPE MAN FILES_MATCHING PATTERN "murmur*")
```suggestion
	install(DIRECTORY "${CMAKE_SOURCE_DIR}/man.1/" TYPE MAN FILES_MATCHING PATTERN "murmur*")
```

2020-09-10 18:54 UTC, davidebeatrici commented
@radioactiveman I agree.

2020-09-11 06:30 UTC, Krzmbrzl commented
Thanks for the inputs. I think have it all covered now :eyes:

2020-09-11 15:21 UTC, merged