FEAT(client): Adds a new shortcut which hides/shows the main window
mumble-voip/mumble pull request #4562
Opened 2020-10-31 22:57 UTC by merua

Implements #2328

2020-11-01 00:37 UTC, davidebeatrici requested changes
I would also remove the log messages.

2020-11-01 00:37 UTC, davidebeatrici commented on src/mumble/MainWindow.cpp
> +		{
```suggestion
	if (down) {
		if (g.mw->isVisible()) {
```

2020-11-01 00:37 UTC, davidebeatrici commented on src/mumble/MainWindow.cpp
> +		{
```suggestion
		} else {
```

2020-11-01 12:12 UTC, Krzmbrzl reviewed
Furthermore you have to update the translations to also include your new string.

In order to do so, please run `scripts/updatetranslations.sh` :point_up:

2020-11-01 18:25 UTC, Krzmbrzl requested changes
Thanks for the changes!

Now I'd only ask you to squash your first 2 commits (but keep the translation one separate) into a single one (the commit history of how the review has influenced the code is nothing that has to go into master).

After that I think we're all set :+1:

2020-11-01 19:07 UTC, davidebeatrici commented on src/mumble/MainWindow.cpp
> +		{
Still the case.

2020-11-02 06:54 UTC, Krzmbrzl approved these changes

2020-11-03 05:13 UTC, davidebeatrici commented on src/mumble/MainWindow.cpp
> +		if(g.mw->isVisible()) {
```suggestion
	if (down) {
		if (g.mw->isVisible()) {
```

2020-11-03 18:15 UTC, davidebeatrici approved these changes

2020-11-03 18:15 UTC, merged

2020-11-03 18:15 UTC, davidebeatrici commented
Thank you very much for your contribution!

2020-11-03 22:38 UTC, merua commented
Thanks to you and all the other contributors.

I have started using Mumble since the lockdowns and it has really helped staying in touch with my friends, so keep up the good work! (Especially since I found out -- to my horror -- that a lot of problem tickets are written in a very toxic tone.)

And next time I will try to set up the formatter. Sorry for that...

2020-11-04 00:08 UTC, davidebeatrici commented
Thanks!

No worries about the formatting, we should probably add a CI task that runs `clang-format` and then shows the changes.