DOCS: Add link to cmake download page
mumble-voip/mumble pull request #4599
Opened 2020-11-26 17:44 UTC by bkmgit

Add a link to the cmake download page where various options for installing cmake can be found.

2020-11-26 18:29 UTC, davidebeatrici commented on docs/dev/build-instructions/build_linux.md
> +[official PPA](https://apt.kitware.com/) or by from the [linked page](https://cmake.org/download/).
```suggestion
[official PPA](https://apt.kitware.com/) or from the [linked page](https://cmake.org/download/).
```

2020-11-26 18:35 UTC, bkmgit commented on docs/dev/build-instructions/build_linux.md
> +[official PPA](https://apt.kitware.com/) or by from the [linked page](https://cmake.org/download/).
Thanks.

2020-11-26 19:08 UTC, Krzmbrzl requested changes
Please squash the 2 commits. After that this LGTM

2020-11-26 20:03 UTC, bkmgit commented
@Krzmbrzl  Assuming no other changes are needed, is it possible to squash commits on merging:
https://github.blog/2016-04-01-squash-your-commits/

2020-11-26 21:39 UTC, davidebeatrici commented
It's possible, but it would not create a merge commit.

2020-11-27 06:06 UTC, bkmgit commented
Thanks. Updated. Is it ok now?

2020-11-27 07:22 UTC, Krzmbrzl approved these changes

2020-11-27 08:16 UTC, merged