FEAT(client): Adds shortcut to listen to a channel
mumble-voip/mumble pull request #4636
Opened 2020-12-15 18:38 UTC by timjwkim

Added a global shortcut that toggles listening to a specific channel targeted by the client. 

Implements #4486

2020-12-18 08:02 UTC, Krzmbrzl requested changes
Please ensure that your commit message follows the format specified in our [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

2020-12-18 08:02 UTC, Krzmbrzl commented on src/mumble/MainWindow.cpp
> +	gsListenChannel = new GlobalShortcut(this, idx++, tr("Listen Channel", "Global Shortcut"));
```suggestion
	gsListenChannel = new GlobalShortcut(this, idx++, tr("Listen to Channel", "Global Shortcut"));
```
Or is that too long to fit in the UI? :thinking:

2020-12-18 08:02 UTC, Krzmbrzl commented on src/mumble/MainWindow.cpp
> +	Channel *c = mapChannel(st.iChannel);
```suggestion
	const Channel *c = mapChannel(st.iChannel);
```

2021-01-06 15:09 UTC, Krzmbrzl commented
@timjwkim are you going to update this PR or shall I finish it up for you?

2021-01-11 19:11 UTC, timjwkim commented
My apologies, didn't get a chance to see the updates on this thread til now.
I will finish up the PR!

2021-06-24 06:32 UTC, Krzmbrzl commented
@timjwkim so?

2021-12-29 21:40 UTC, kol0 commented
@Krzmbrzl What can I do to push this change forward?
I would love to be able to set up channel listening with hotkeys.

2022-01-01 15:30 UTC, Krzmbrzl commented
@kol0 as it stands I think it would be fine, if you forked @timjwkim repo and pick up the work from where it was left. As long as you don't remove @timjwkim from the commit authorship (but add yourself), I think that should be fine.

2022-09-09 11:07 UTC, Krzmbrzl approved these changes
I took the liberty of finishing this PR myself. In the end it did turn out to be a bit more complicated than originally anticipated due to the way server-specfic global shortcuts were handled up to know.

2022-09-09 12:01 UTC, merged