FIX(client): Image not supported error message wrongly displayed,
mumble-voip/mumble pull request #4661
Opened 2021-01-01 11:28 UTC by TerryGeng

Fixed: "This server does not allow sending images" displayed no matter if images are in the pasted content when pasting contents into the chatbar.

Fixed #4660.

2021-01-02 18:07 UTC, Krzmbrzl requested changes
The changes LGTM.

Could you re-format your commit message a bit though? Imo the header should not start a sentence that then continues in the body. I would propose something like this:
```
FIX(client): Wrong "Image not supported" message

As of 3d2a196830e9a71590100594595d89591c048b06 the client would always log
"This server does not allow sending images." to the console when pasting anything
to the chatbar (regardless of whether it actually contains an image) if the client is connected
to a server that doesn't allow HTML messages.

Fixes #4660
```

2021-01-03 01:38 UTC, TerryGeng commented
@Krzmbrzl Sounds a little bit too heavy for such a little bug fix, but will do ;)

2021-01-03 11:15 UTC, Krzmbrzl commented
> Sounds a little bit too heavy for such a little bug fix

Well it's always best to explain what the error was and where it came from so that if someone is looking at that code again and searches the git history, that person will easily understand why the changes where made in this way. I always opt towards being e bit more verbose than strictly necessary in order to allow for that :)

2021-01-03 11:16 UTC, Krzmbrzl approved these changes

2021-01-03 11:16 UTC, merged

2021-01-03 11:18 UTC, Krzmbrzl commented
Thanks for the quick fix! :+1: 

Iirc on IRC you also wrote about a line break before images that was added before but is not added anymore. This can be viewed as a regression as well. It was not intentionally removed. It simply slipped through my review.
Do you think we should add that back in? (and what exactly did it do? Simply adding a line break in front of an image so it's on its own line?)

2021-01-04 14:19 UTC, TerryGeng commented
@Krzmbrzl I re-examined the code and discovered the missing "<br>" part was actually moved elsewhere, not deleted.
Further testing indicated that it works fine. The spacing of the image is good. I think no further action needed by now.

2021-01-04 14:23 UTC, Krzmbrzl commented
Ah, even better. Thanks for taking a look :)