Replace call to processEvents with sendPostedEvents in accordance with the Qt documentation
mumble-voip/mumble pull request #4833
Opened 2021-03-06 19:41 UTC by chili-b

Replace call to processEvents with call to sendPostedEvents as suggested by https://doc.qt.io/qt-5/qcoreapplication.html#processEvents. 

As per the docs: "In the event that you are running a local loop which calls this function continuously, without an event loop, the DeferredDelete events will not be processed. This can affect the behaviour of widgets, e.g. QToolTip, that rely on DeferredDelete events to function properly. An alternative would be to call sendPostedEvents() from within that local loop." 

This change appears to resolve an issue where the loop in the read method never exits which freezes Murmur.

### Checks

- [ ] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

2021-03-06 23:00 UTC, MaxwellCody approved these changes

2021-03-07 12:58 UTC, Krzmbrzl requested changes
> My commits follow the commit guidelines

No they don't. Why did you check that checkbox?

I don't see why this would resolve the described issue. Could you provide a bit more context and insights into that please?

Also the changed code seems to do something different than the original code that excluded socket events and restricted the time for processing events to 100ms for each iteration. While I don't know the reasoning for why this was chosen, I think I would like to hear some reasoning as to why this was changed here :thinking:

2021-03-07 16:44 UTC, chili-b commented
I have some software that uses gRPC's filter stream. Without this change, after some period of time the response for a message is never received (even though my code sends it) and the server ends up waiting forever. 

The change I've made resolves this for my server.

I replaced the method call since it seemed like the documentation indicated that it would be preferable to use sendPostedEvents when a local loop is used instead of a proper event loop. I'm fairly certain that the root issue is to do with the 100ms restriction as exceeding it seemed to cause the indefinite hang.

I'm not saying I'm not missing anything, but the restriction on the event types didn't seem to do anything. With its exclusion, I can still open and close the filter stream (and other streams) and the server operates normally.

2021-03-07 17:58 UTC, Krzmbrzl commented
Hm I definitely would prefer actually understanding what the cause of the issue was in the first place and _why_ the changes made seems to resolve them.
But on the other hand the gRPC interface is not declared to be stable in any way, shape or form anyways, so I guess blindly applying the fix doesn't do much harm either :thinking: 

@davidebeatrici thoughts?

2021-03-07 18:19 UTC, davidebeatrici commented
Looks good to me.

2021-03-07 18:23 UTC, Krzmbrzl commented
Alright then. @chili-b could you adapt your commit to follow our commit guidelines, please? It should start with `FIX(grpc): ` and then please include the reasoning that you have written in this PR into the message's body.
After that we can merge this :+1:

2021-03-08 16:44 UTC, chili-b commented
> Alright then. @chili-b could you adapt your commit to follow our commit guidelines, please? It should start with `FIX(grpc): ` and then please include the reasoning that you have written in this PR into the message's body.
> After that we can merge this +1

Okay, I think I've done it. Please tell me if anything else is missinge.

2021-03-08 17:42 UTC, Krzmbrzl commented
> Okay, I think I've done it.

Unfortunately you haven't. In fact you did not change your commit at all :eyes: 

See https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message for how commit messages can be edited.

2021-03-08 18:07 UTC, chili-b commented
Okay, I have done it for real this time.

2021-03-08 18:51 UTC, Krzmbrzl approved these changes

2021-03-08 19:29 UTC, davidebeatrici approved these changes

2021-03-08 19:57 UTC, merged

2021-03-08 19:58 UTC, Krzmbrzl commented
Thank you for this fix :+1: