TRANSLATION: Small fixes and cleanup on updatetranslations script
mumble-voip/mumble pull request #4837
Opened 2021-03-07 22:49 UTC by Kissaki

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

2021-03-08 09:09 UTC, Krzmbrzl requested changes
None of the commits is about translations (directly) and thus their TYPE should be `MAINT` instead

2021-03-08 17:43 UTC, Kissaki commented
I fixed the commit TYPEs.

2021-03-08 17:47 UTC, Krzmbrzl commented
Now the commit titles are a bit non-telling though (there is no reference of the translatin script in them). I think this could be fixed by appending `in updatetranslations.py` to all commit titles

2021-03-09 15:01 UTC, Krzmbrzl approved these changes

2021-03-09 15:02 UTC, merged