Replace non-standard u_char with unsigned_char
mumble-voip/mumble pull request #4885
Opened 2021-03-26 22:52 UTC by lorenz

u_char is an old nonstandard BSD alias and should not be used in portable code.

For example the musl libc doesn't provide this alias.

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

2021-03-26 23:04 UTC, davidebeatrici approved these changes

2021-03-26 23:05 UTC, davidebeatrici commented
`uint8_t` would be even better in my opinion.

2021-03-26 23:08 UTC, lorenz commented
@davidebeatrici done :)

2021-03-26 23:19 UTC, davidebeatrici commented
Thanks!

2021-03-27 07:30 UTC, Krzmbrzl requested changes
Your commit's type should be `REFAC(server)` instead of `FIX` :point_up:

2021-03-27 07:36 UTC, davidebeatrici commented
Also, `unsigned char` is now `uint8_t`.

2021-03-27 21:26 UTC, Krzmbrzl approved these changes

2021-03-27 21:47 UTC, merged