fix(docs): corrects typos in project documentation
mumble-voip/mumble pull request #4942
Opened 2021-04-24 04:46 UTC by plan-do-break-fix

Scope of changes is restricted to docs only. 

### Checks

- [x ] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

2021-04-24 06:54 UTC, Krzmbrzl requested changes
The changes LGTM.

Could you reword your commit message to
```
DOCS: Fixed typos
```
please?

2021-04-27 07:31 UTC, Kissaki approved these changes

2021-05-02 21:24 UTC, Kissaki commented
I adjusted the commit message

2021-05-03 05:54 UTC, Krzmbrzl approved these changes

2021-05-06 16:15 UTC, merged

2021-05-06 16:15 UTC, Krzmbrzl commented
Thanks for fixing this :+1: