FIX(client): Windows loading/saving shortcuts
mumble-voip/mumble pull request #4976
Opened 2021-05-09 07:41 UTC by Septarius

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### Issues

This pull request fixes the following issues:

The revamped raw inputs are not saving / loading shortcuts for the Windows client.

Keyboard shortcuts that are outside of the normal range show up as "Unknown"

### Tested

- [x] InputXinput (Xbox controller)
- [x] InputKeyboard (Normal and "Unknown" characters)
- [x] InputMouse
- [ ] InputHid
- [ ] InputGKey

I don't have a controller that works under InputHid.
I don't believe InputGKey is compatible with my mouse under Logitech GHub.

![image](https://user-images.githubusercontent.com/1136966/117564030-1d063c00-b067-11eb-812d-152c1d757f6d.png)

1. Shows M3 for Mouse3, 
2. K118 is "F24" on the keyboard which is mapped from mouse using Logitech GHub, 
3. Xbox1:A is the Xinput Xbox controller's A.

### Notes

This could be considered a breaking change since the shortcut save format might not be backwards compatible. Though that format change had already been made, this fixes it so the change persists to disk.
It is also difficult to reload a previous version's shortcuts to be sure what would be backwards compatible.

- FIX(client): Add and register stream operators to the Input structs

Step 1 to fix Windows loading / saving shortcuts since 3dc7b00
Adds the stream operators to the Input structs and a call to register them in Settings.cpp
The metatypes have to be registered in Settings.cpp because it runs before GlobalShortcuts are initialized. Without being registered it will not load the Input buttons.

- FIX(client): Debug Assertion Failed in getPlugins

Expression: invalid comparator
Thrown when opening the Settings window.
This started happening when I had multiple shortcuts defined and running in debug mode.

- FIX(client): lnt-uninitialized-local in GlobalShortcut_win

lnt-uninitialized-local errors were preventing InputKeyboard shortcuts from being detected/fired after relaunch.
When initially setup they would work until the client was relaunched.

- FEAT(client): Show scan code for InputKeyboard when GetKeyNameText fails

For keys like F13 - F24 where GetKeyNameText doesn't have a label.
Use similar technique to the InputMouse to show something other than "Unknown"

2021-05-09 16:09 UTC, Krzmbrzl requested changes
I think your first commit should be of type `CODE` instead of `FIX`.

2021-05-09 16:09 UTC, Krzmbrzl commented
@davidebeatrici consider the changes made to `PluginManager.cpp` to be approved (thanks for finding that @Septarius :)).

2021-05-09 17:27 UTC, davidebeatrici commented on src/mumble/GlobalShortcut_win.h
> +	static void registerMetaTypes();
I would move this at the top and leave en empty line below:
```cpp
static void registerMetaTypes();

/// Inject a native Windows raw input message into GlobalShortcutWin's
/// thread. This method is meant to be called from the main thread
/// to pass native Windows keyboard messages to GlobalShortcutWin.
///
/// @param msg The raw input handle to inject into GlobalShortcutWin.
void injectRawInputMessage(HRAWINPUT handle);
```

2021-05-09 17:35 UTC, davidebeatrici commented on src/mumble/GlobalShortcut_win.cpp
> +			// If GetKeyNameText cannot find the name. Show a K prefix and the scan code instead of Unknown.
```suggestion
			// If GetKeyNameText() cannot find the name. Show a K prefix and the scan code instead of Unknown.
```

2021-05-09 17:36 UTC, davidebeatrici commented
> I don't have a controller that works under InputHid.

Xbox controllers are supported through raw input, you just have to disable XInput.

2021-05-10 07:02 UTC, davidebeatrici commented
Thanks for addressing my comments!

There was no need to set me as co-author for 11f96da31ce3155d27eff5ddc1678044180ceb72, I only suggested to move a function declaration after all.

2021-05-10 07:02 UTC, davidebeatrici approved these changes

2021-05-10 07:05 UTC, Septarius commented
Ok, I did add the additional commit to fix InputHid since I was able to test that one.

2021-05-10 12:04 UTC, Krzmbrzl commented
@Septarius I have to apologize: I advised you to use the `CODE` tag where I should have advised to use `REFAC` instead as there is no `CODE` type according to our [guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md) :see_no_evil:

2021-05-11 01:37 UTC, Septarius commented
No problem, fixed the commit summaries. Removed the errant co-author footers.
Format document didn't run on the last commit (1a04a17), so line 68 is now correct.
Thanks!

2021-05-11 10:34 UTC, merged