FIX(client): Positional audio not working properly after canceling audio wizard
mumble-voip/mumble pull request #5035
Opened 2021-05-23 21:47 UTC by davidebeatrici

`bPosTest` is a flag we use to indicate that we're in the middle of a test.

It freezes the user's direction vector so that it always "looks" straight ahead.

When completing the wizard, `accept()` is called and thus the variable is set to false again.

However, when the wizard is closed prematurely, `reject()` is called instead.

2021-05-26 10:46 UTC, Krzmbrzl requested changes
Your commit message only explains a single line of the changes and yet there are multiple other changes that are being introduced.
Either these should be in a separate commit with a separate explanation or the current commit's description needs to be extended to include reasoning for the extra changes :eyes:

2021-05-26 18:28 UTC, davidebeatrici commented
I moved the lines to match the order in `AudioWizard::accept()`.

2021-05-27 07:37 UTC, Krzmbrzl commented
Ah okay I see. For the sake of clarity, I think these should be two commits nonetheless. First a REFAC that adapts the ordering of the lines and then a second IFX commit that actually adds the line for the fix.

2021-05-27 12:58 UTC, Krzmbrzl approved these changes

2021-05-27 13:00 UTC, merged