FEAT(client): Add StartupWMClass to .desktop file
mumble-voip/mumble pull request #5197
Opened 2021-07-17 20:46 UTC by koyuawsmbrtn

This adds the StartupWMClass to the .desktop file which allows pinning Mumble to the dash/dock/whatever in all major desktop environments. Since most package maintainers ship their own .desktop file where this is fixed this fixes it for everyone who compiles Mumble from source.

### Checks

- [ ] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

2021-07-18 11:18 UTC, Krzmbrzl requested changes
Could you please change the TYPE and scope of your commit message to `MAINT` or `MAINT(desktop-file)`?

`FEAT` is reserved for actual features of the software whereas this is a change in an auxiliary file :)

2021-07-18 14:02 UTC, koyuawsmbrtn commented
> Could you please change the TYPE and scope of your commit message to `MAINT` or `MAINT(desktop-file)`?
> 
> `FEAT` is reserved for actual features of the software whereas this is a change in an auxiliary file :)

Done!

2021-07-18 14:40 UTC, Krzmbrzl commented
Oh no - I didn't mean to scratch the rest of the commit message. That was great. I only wanted you to change the TYPE and scope :sweat_smile:

2021-07-18 15:42 UTC, koyuawsmbrtn commented
Yeah I did an `--amend` and apparently it didn't transfer my commit message properly. I'll fix than soon.

2021-07-24 11:29 UTC, merged

2021-07-24 11:30 UTC, Krzmbrzl commented
Thank you for your contribution :+1: