FEAT(client): Add opus as output format for recording
mumble-voip/mumble pull request #5251
Opened 2021-09-01 09:00 UTC by evris99

This commits adds opus as an output format for voice recordings as requested in #5065. It uses an OGG container like the already implemented Vorbis codec but has much better compression. For clarity the .opus file extension is used.

Implements #5065

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

2021-09-01 11:12 UTC, Krzmbrzl commented
Changes LGTM now but we will have to figure out why this doesn't work on Linux. Maybe we'll have to introduce an option for this that is OFF by default on Linux :thinking: 
But before doing that I would like to find out why it seems that the Linux version of libsndfile seems to ship without Opus support.

2021-09-01 12:46 UTC, evris99 commented
I see that the support for opus files was added in `libsndfile` version 1.0.29 from [here](https://github.com/libsndfile/libsndfile/releases/tag/v1.0.29). But Ubuntu versions less than 21.04 use a previous version of the library ([source](https://packages.ubuntu.com/source/groovy/libsndfile)).

2021-09-01 15:06 UTC, Krzmbrzl commented
Ah yes that could explain it.

It seems that Ubuntu 20.04 ships version 1.0.28. The cmake output agrees with this observation.

Because of this I would suggest to following: Check whether the libsndfile version is >= 1.0.29 here:
https://github.com/mumble-voip/mumble/blob/207dbe0d8adffb24b807a7f1d39165a81e59785e/src/mumble/CMakeLists.txt#L452-L463
I assume that the found version is written to `SndFile_VERSION` so you should be able to use that to check for the version.

If the version is >= 1.0.29, then add a global macro definition `USE_SNDFILE_OPUS` and then encapsulate all of your changes with `#ifdef USE_SNDFILE_OPUS` blocks.

That should include this feature if the used sndfile-library is recent enough to support it.

2021-09-01 17:21 UTC, evris99 commented
Any ideas as to why the macOS workflows fail?

2021-09-01 18:09 UTC, Krzmbrzl requested changes

2021-09-01 18:09 UTC, Krzmbrzl commented on src/mumble/CMakeLists.txt
> +if(${sndfile_VERSION} STRGREATER_EQUAL "1.0.29")
```suggestion
if("${sndfile_VERSION}" VERSION_GREATER_EQUAL "1.0.29")
```

2021-09-01 18:09 UTC, Krzmbrzl commented on src/mumble/CMakeLists.txt
> +    add_compile_definitions(USE_SNDFILE_OPUS)
```suggestion
   target_compile_definitions(mumble PRIVATE USE_SNDFILE_OPUS)
```

2021-09-01 18:09 UTC, Krzmbrzl commented on src/mumble/CMakeLists.txt
> +endif()
```suggestion
else()
	message(WARNING "libsnfile is missing Opus-support -> No Opus-format recording")
endif()
```

2021-09-01 18:10 UTC, Krzmbrzl commented
> Any ideas as to why the macOS workflows fail?

Because macOS is weird? :sweat_smile: 

Don't worry though - it just does this sometimes (we don't know why or when). It should be unrelated to your changes though. The important bit (building) succeeded.

2021-09-02 18:12 UTC, Krzmbrzl commented
It seems like in your first commit the description of what was done went missing. Please use the same description for the commit as you did for this PR (including the Fixes xxx line) :)

2021-09-03 06:20 UTC, Krzmbrzl approved these changes

2021-09-03 07:49 UTC, merged

2021-09-03 07:50 UTC, Krzmbrzl commented
Thank you very much for your contribution :+1:

2021-09-03 10:58 UTC, evris99 commented
Thank you for your help