DOCS: Updated build instructions to remove duplicated step
mumble-voip/mumble pull request #5467
Opened 2022-01-18 20:55 UTC by brigzzy

DOCS: Updated build instructions to remove duplicated step

There's a duplicated step in the build instructions, which is already covered on line 8.  This change removes the unneeded duplicate step.

2022-01-18 20:58 UTC, Krzmbrzl requested changes
Please reword your commit message to what you used as PR description. Then then formatting will be correct. As it stands, the commit doesn't conform to our commit guidelines

2022-01-18 21:03 UTC, brigzzy commented
@Krzmbrzl Thanks for the quick reply!  I'm not super git savvy, but I think the commit message has been updated.  Please let me know if it's still not looking correct :)

2022-01-19 07:16 UTC, Krzmbrzl reviewed
Yep, that is looking good now :+1:

2022-01-19 07:16 UTC, Krzmbrzl approved these changes

2022-01-19 07:16 UTC, merged

2022-01-19 07:17 UTC, Krzmbrzl commented
Thanks for fixing this :+1:

2022-01-19 16:47 UTC, brigzzy commented
No problem, thanks for merging it!