FIX(positional-audio): add missing <memory> include
mumble-voip/mumble pull request #5587
Opened 2022-02-27 11:03 UTC by trofi

Without the change the build fails on upcoming gcc-12 as:

    /build/mumble/plugins/gtav/gtav.cpp:13:13:
      error: 'unique_ptr' in namespace 'std' does not name a template type
       13 | static std::unique_ptr< Game > game;
          |             ^~~~~~~~~~
    /build/mumble/plugins/gtav/gtav.cpp:12:1:
      note: 'std::unique_ptr' is defined in header '<memory>';
        did you forget to '#include <memory>'?
       11 | #include <cstring>
      +++ |+#include <memory>
       12 |

### Checks

- [x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

2022-02-27 14:47 UTC, Krzmbrzl requested changes
Would you mind changing your commit type to `BUILD` instead of `FIX`? The latter is used exclusively for fixing bugs in the software (aka the compiled binary). Since this fixes something along the way to actually get to the binary, this affects the BUILD instead.

So e.g.
```
BUILD(positional-audio): Fix missing <memory> include
```

2022-02-27 17:25 UTC, trofi commented
Sounds good! Changed commit name and pull request name to `BUILD(positional-audio): Fix missing <memory> include`.

2022-02-27 18:01 UTC, Krzmbrzl approved these changes

2022-02-27 18:24 UTC, merged

2022-02-27 18:24 UTC, Krzmbrzl commented
Thanks for fixing this :+1:

2022-05-08 07:16 UTC, Krzmbrzl commented
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|1.4.x|[<img src="https://img.shields.io/github/pulls/detail/state/mumble-voip/mumble/5655">](https://github.com/mumble-voip/mumble/pull/5655)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

<!--- Backport version: 8.4.0 -->