Add hotkey/toolbar icon to toggle RNNoise
mumble-voip/mumble pull request #5911
Opened 2022-10-02 01:08 UTC by sethbrown246

### Checks

FEAT(ToggleRNNoise)

Hello, these are the changes I have made so far for trying to implement a global shortcut to toggle RNNoise. I believe the only thing left for me to do is to change Settings::noiseCancelMode but I was not sure how to do that. Let me know if what I have so far is good and if you have any tips on how to change Settings::noiseCancelMode to finish this issue. 

Thanks in advance! 

Implements #4189 

- [ ] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

2022-10-02 01:12 UTC, davidebeatrici commented
The concept is correct, however I would add a shortcut to cycle through all noise cancellation methods instead.

2022-10-03 08:25 UTC, Krzmbrzl requested changes
Please try to make sure that your commits follow our commit guidelines.

2022-10-03 08:25 UTC, Krzmbrzl commented on .github/workflows/build.yml
> -
Unrelated change

2022-10-03 08:25 UTC, Krzmbrzl commented on sonar-project.properties
> +sonar.projectKey=sethbrown246_mumble
Unrelated changes

2022-12-28 13:48 UTC, Krzmbrzl commented
@sethbrown246 what is your plan with this PR? Do you want to finish it?

2023-12-31 08:16 UTC, Krzmbrzl commented
Closing this in light of #6292

2023-12-31 08:16 UTC, closed without merging