FIX(client): Prevent local muted users from triggering attenuation
mumble-voip/mumble pull request #6394
Opened 2024-04-14 17:23 UTC by jlallas384

When 'while others users talk' attenuation is enabled, unmuted users still trigger attenuation even if they are locally muted.

The fix is don't add local muted users' audio source to the mixing for the audio output

Fixes #6247

### Checks

- [X] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

2024-04-16 17:34 UTC, Krzmbrzl reviewed
Note that this also changes the behavior in that audio samples for cases where `user == nullptr`  are discarded whereas before they were still added to `qlMix`.
That's probably okay though 👀

2024-04-16 17:34 UTC, Krzmbrzl commented on src/mumble/AudioOutput.cpp
> +					prioritySpeakerActive = true;
```suggestion
				prioritySpeakerActive = user->bPrioritySpeaker;
```

2024-04-16 18:04 UTC, Hartmnt commented
> Note that this also changes the behavior in that audio samples for cases where `user == nullptr` are discarded whereas before they were still added to `qlMix`. That's probably okay though 👀

This could be a problem for sound file samples... I would have first to look at the code again to confirm though

2024-04-16 18:41 UTC, Krzmbrzl commented
Oh indeed - totally missed that!

2024-04-17 09:16 UTC, Hartmnt requested changes
This change does indeed prevent any sound files (audio cues and notification sounds) from playing.

You have to make sure that samples without a valid user pointer are also added to qlMix

2024-04-17 15:24 UTC, Hartmnt requested changes
This almost works, but not quite.

Audio samples are now played correctly, and application attenuation is handled gracefully.
However, local muting a priority speaker has no effect now. Which means other users are still locally attenuated, if a locally muted PS speaks.

I think it should be enough to move the !localMute condition to the last else

2024-06-02 14:34 UTC, Hartmnt commented
@jlallas384 Do you still have the time and motivation to finish this?

2025-03-07 17:52 UTC, Hartmnt commented
Superseded by #6747

2025-03-07 17:52 UTC, closed without merging