FEAT: Add Qt 6 support
mumble-voip/mumble pull request #6516
Opened 2024-07-20 23:10 UTC by davidebeatrici

Requires thorough testing, especially the regex changes.

2024-07-20 23:12 UTC, davidebeatrici commented
Patch to switch from Qt 5 to Qt 6 in CMake:

```patch
diff --git a/helpers/g15helper/CMakeLists.txt b/helpers/g15helper/CMakeLists.txt
index 16a85418d..79007683b 100644
--- a/helpers/g15helper/CMakeLists.txt
+++ b/helpers/g15helper/CMakeLists.txt
@@ -28,14 +28,14 @@ set_target_properties(g15-helper
 target_compile_definitions(g15-helper PRIVATE $<$<CONFIG:Debug>:USE_LOGFILE>)
 
 if(g15-emulator)
-	find_pkg(Qt5 COMPONENTS Core Gui Widgets REQUIRED)
+	find_pkg(Qt6 COMPONENTS Core Gui Widgets REQUIRED)
 	set_target_properties(g15-helper PROPERTIES AUTOMOC ON)
 	target_sources(g15-helper PRIVATE "g15helper_emu.cpp" "g15helper_emu.h")
-	target_link_libraries(g15-helper PRIVATE Qt5::Core Qt5::Gui Qt5::Widgets)
+	target_link_libraries(g15-helper PRIVATE Qt6::Core Qt6::Gui Qt6::Widgets)
 
-	if(static AND WIN32 AND TARGET Qt5::QWindowsIntegrationPlugin)
+	if(static AND WIN32 AND TARGET Qt6::QWindowsIntegrationPlugin)
 		include_qt_plugin(g15-helper PRIVATE QWindowsIntegrationPlugin)
-		target_link_libraries(g15-helper PRIVATE Qt5::QWindowsIntegrationPlugin)
+		target_link_libraries(g15-helper PRIVATE Qt6::QWindowsIntegrationPlugin)
 	endif()
 else()
 	if(MSVC)
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index f1b7cb02d..90b94fddc 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -17,7 +17,7 @@ option(tracy "Enable the tracy profiler." OFF)
 option(bundled-gsl "Use the bundled GSL version instead of looking for one on the system" ON)
 
 
-find_pkg(Qt5
+find_pkg(Qt6
 	COMPONENTS
 		Core
 		Network
@@ -176,9 +176,9 @@ target_link_libraries(shared
 		protobuf::libprotobuf
 		OpenSSL::Crypto
 		OpenSSL::SSL
-		Qt5::Core
-		Qt5::Network
-		Qt5::Xml
+		Qt6::Core
+		Qt6::Network
+		Qt6::Xml
 )
 
 if(WIN32)
diff --git a/src/mumble/CMakeLists.txt b/src/mumble/CMakeLists.txt
index fa41283bc..65616c6d1 100644
--- a/src/mumble/CMakeLists.txt
+++ b/src/mumble/CMakeLists.txt
@@ -73,7 +73,7 @@ if(MSVC)
 	option(elevation "Set \"uiAccess=true\", required for global shortcuts to work with privileged applications. Requires the client's executable to be signed with a trusted code signing certificate." OFF)
 endif()
 
-find_pkg(Qt5
+find_pkg(Qt6
 	COMPONENTS
 		Concurrent
 		Sql
@@ -540,24 +540,24 @@ endif()
 target_link_libraries(mumble_client_object_lib
 	PUBLIC
 		shared
-		Qt5::Concurrent
-		Qt5::Sql
-		Qt5::Svg
-		Qt5::Widgets
+		Qt6::Concurrent
+		Qt6::Sql
+		Qt6::Svg
+		Qt6::Widgets
 )
 
 if(static)
-	if(TARGET Qt5::QSQLiteDriverPlugin)
+	if(TARGET Qt6::QSQLiteDriverPlugin)
 		include_qt_plugin(mumble_client_object_lib PRIVATE "QSQLiteDriverPlugin")
-		target_link_libraries(mumble_client_object_lib PUBLIC Qt5::QSQLiteDriverPlugin)
+		target_link_libraries(mumble_client_object_lib PUBLIC Qt6::QSQLiteDriverPlugin)
 	endif()
-	if(TARGET Qt5::QSvgIconPlugin)
+	if(TARGET Qt6::QSvgIconPlugin)
 		include_qt_plugin(mumble_client_object_lib PRIVATE "QSvgIconPlugin")
-		target_link_libraries(mumble_client_object_lib PUBLIC Qt5::QSvgIconPlugin)
+		target_link_libraries(mumble_client_object_lib PUBLIC Qt6::QSvgIconPlugin)
 	endif()
-	if(TARGET Qt5::QSvgPlugin)
+	if(TARGET Qt6::QSvgPlugin)
 		include_qt_plugin(mumble_client_object_lib PRIVATE "QSvgPlugin")
-		target_link_libraries(mumble_client_object_lib PUBLIC Qt5::QSvgPlugin)
+		target_link_libraries(mumble_client_object_lib PUBLIC Qt6::QSvgPlugin)
 	endif()
 endif()
 
@@ -595,9 +595,9 @@ if(WIN32)
 		REQUIRED
 	)
 
-	if(static AND TARGET Qt5::QWindowsIntegrationPlugin)
+	if(static AND TARGET Qt6::QWindowsIntegrationPlugin)
 		include_qt_plugin(mumble_client_object_lib PRIVATE QWindowsIntegrationPlugin)
-		target_link_libraries(mumble_client_object_lib PUBLIC Qt5::QWindowsIntegrationPlugin)
+		target_link_libraries(mumble_client_object_lib PUBLIC Qt6::QWindowsIntegrationPlugin)
 	endif()
 
 	add_subdirectory("${3RDPARTY_DIR}/SPSCQueue" "${CMAKE_CURRENT_BINARY_DIR}/SPSCQueue" EXCLUDE_FROM_ALL)
@@ -647,9 +647,9 @@ else()
 			target_compile_definitions(mumble_client_object_lib PUBLIC "NO_XINPUT2")
 		endif()
 
-		if(static AND TARGET Qt5::QXcbIntegrationPlugin)
+		if(static AND TARGET Qt6::QXcbIntegrationPlugin)
 			include_qt_plugin(mumble_client_object_lib PRIVATE QXcbIntegrationPlugin)
-			target_link_libraries(mumble_client_object_lib PUBLIC Qt5::QXcbIntegrationPlugin)
+			target_link_libraries(mumble_client_object_lib PUBLIC Qt6::QXcbIntegrationPlugin)
 		endif()
 
 		target_sources(mumble_client_object_lib
@@ -684,9 +684,9 @@ else()
 				"os_macx.mm"
 		)
 
-		if(static AND TARGET Qt5::QCocoaIntegrationPlugin)
+		if(static AND TARGET Qt6::QCocoaIntegrationPlugin)
 			include_qt_plugin(mumble_client_object_lib PRIVATE QCocoaIntegrationPlugin)
-			target_link_libraries(mumble_client_object_lib PUBLIC Qt5::QCocoaIntegrationPlugin)
+			target_link_libraries(mumble_client_object_lib PUBLIC Qt6::QCocoaIntegrationPlugin)
 		endif()
 
 		target_link_libraries(mumble_client_object_lib
@@ -768,9 +768,9 @@ if(renamenoise)
 endif()
 
 if(qtspeech)
-	find_pkg(Qt5 COMPONENTS TextToSpeech REQUIRED)
+	find_pkg(Qt6 COMPONENTS TextToSpeech REQUIRED)
 	target_sources(mumble_client_object_lib PRIVATE "TextToSpeech.cpp")
-	target_link_libraries(mumble_client_object_lib PUBLIC Qt5::TextToSpeech)
+	target_link_libraries(mumble_client_object_lib PUBLIC Qt6::TextToSpeech)
 elseif(WIN32)
 	target_sources(mumble_client_object_lib PRIVATE "TextToSpeech_win.cpp")
 	if(MINGW)
@@ -821,7 +821,7 @@ if(NOT update)
 endif()
 
 if(NOT WIN32 AND NOT APPLE)
-	find_pkg(Qt5 COMPONENTS DBus REQUIRED)
+	find_pkg(Qt6 COMPONENTS DBus REQUIRED)
 
 	target_sources(mumble_client_object_lib
 		PRIVATE
@@ -830,7 +830,7 @@ if(NOT WIN32 AND NOT APPLE)
 	)
 	
 	target_compile_definitions(mumble_client_object_lib PUBLIC "USE_DBUS")
-	target_link_libraries(mumble_client_object_lib PUBLIC Qt5::DBus)
+	target_link_libraries(mumble_client_object_lib PUBLIC Qt6::DBus)
 endif()
 
 if(translations)
diff --git a/src/murmur/CMakeLists.txt b/src/murmur/CMakeLists.txt
index 1916db4ec..bacf8c504 100644
--- a/src/murmur/CMakeLists.txt
+++ b/src/murmur/CMakeLists.txt
@@ -16,7 +16,7 @@ include(qt-utils)
 
 option(ice "Build support for Ice RPC." ON)
 
-find_pkg(Qt5 COMPONENTS Sql REQUIRED)
+find_pkg(Qt6 COMPONENTS Sql REQUIRED)
 
 set(MURMUR_SOURCES
 	"main.cpp"
@@ -78,32 +78,32 @@ target_include_directories(mumble-server PRIVATE
 	${SHARED_SOURCE_DIR}
 )
 
-target_link_libraries(mumble-server PRIVATE shared Qt5::Sql)
+target_link_libraries(mumble-server PRIVATE shared Qt6::Sql)
 
 if(static)
 	# MariaDB and MySQL
-	if(TARGET Qt5::QMYSQLDriverPlugin)
+	if(TARGET Qt6::QMYSQLDriverPlugin)
 		include_qt_plugin(mumble-server PRIVATE "QMYSQLDriverPlugin")
-		target_link_libraries(mumble-server PRIVATE Qt5::QMYSQLDriverPlugin)
+		target_link_libraries(mumble-server PRIVATE Qt6::QMYSQLDriverPlugin)
 	endif()
 	# Open DataBase Connectivity
-	if(TARGET Qt5::QODBCDriverPlugin)
+	if(TARGET Qt6::QODBCDriverPlugin)
 		include_qt_plugin(mumble-server PRIVATE "QODBCDriverPlugin")
-		target_link_libraries(mumble-server PRIVATE Qt5::QODBCDriverPlugin)
+		target_link_libraries(mumble-server PRIVATE Qt6::QODBCDriverPlugin)
 		if(WIN32)
 			find_library(LIB_ODBC32 "odbc32")
 			target_link_libraries(mumble-server PRIVATE ${LIB_ODBC32})
 		endif()
 	endif()
 	# PostgreSQL
-	if(TARGET Qt5::QPSQLDriverPlugin)
+	if(TARGET Qt6::QPSQLDriverPlugin)
 		include_qt_plugin(mumble-server PRIVATE "QPSQLDriverPlugin")
-		target_link_libraries(mumble-server PRIVATE Qt5::QPSQLDriverPlugin)
+		target_link_libraries(mumble-server PRIVATE Qt6::QPSQLDriverPlugin)
 	endif()
 	# SQLite
-	if(TARGET Qt5::QSQLiteDriverPlugin)
+	if(TARGET Qt6::QSQLiteDriverPlugin)
 		include_qt_plugin(mumble-server PRIVATE "QSQLiteDriverPlugin")
-		target_link_libraries(mumble-server PRIVATE Qt5::QSQLiteDriverPlugin)
+		target_link_libraries(mumble-server PRIVATE Qt6::QSQLiteDriverPlugin)
 	endif()
 endif()
 
@@ -125,19 +125,19 @@ if(WIN32)
 			AUTORCC ON
 	)
 
-	find_pkg(Qt5 COMPONENTS Widgets REQUIRED)
+	find_pkg(Qt6 COMPONENTS Widgets [...]

2024-07-21 05:51 UTC, Krzmbrzl requested changes
Haven't looked through all changes yet.

How did you manage the C++17 dependency though?

2024-07-21 05:51 UTC, Krzmbrzl commented on src/Group.cpp
> +		auto requiredChannelIndex = currentChannelHierarchy.indexOf(contextChannel);
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/Group.cpp
> +		const auto minDepth = requiredChannelIndex + minDescendantLevel;
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/Group.cpp
> +		const auto maxDepth = requiredChannelIndex + maxDescendantLevel;
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/Group.cpp
> +		const auto totalDepth = homeChannelHierarchy.count() - 1;
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/ProcessResolver.cpp
> +				const auto nul = cmdline.indexOf('\0');
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/ProcessResolver.cpp
> +					const auto lastBackslash = exe.lastIndexOf(QLatin1String("\\"));
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/SSL.cpp
> +#if QT_VERSION < 0x060300
Maybe just remove these for good?

2024-07-21 05:51 UTC, Krzmbrzl commented on src/ServerResolver.cpp
> +#if QT_VERSION >= 0x060000
Imo we should fully switch to Qt6

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/ACLEditor.cpp
> +	const auto idx = qlACLs.indexOf(as);
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/ACLEditor.cpp
> +	const auto idx = qlACLs.indexOf(as) + 1;
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/API_v_1_x_x.cpp
> +#if QT_VERSION >= 0x060000
I'd keep only the Qt6 variant

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/AudioConfigDialog.cpp
> +	const auto index = keys.indexOf(AudioInputRegistrar::current);
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/AudioConfigDialog.cpp
> +	const auto index = keys.indexOf(AudioOutputRegistrar::current);
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/ConnectDialog.cpp
> +#if QT_VERSION >= 0x060000
Keep only Qt6

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/ConnectDialog.cpp
> +		const auto schemaPos = server.indexOf(QLatin1String("://"));
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/ConnectDialog.cpp
> +		const auto pathPos = server.indexOf(QLatin1Char('/'));
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/ConnectDialog.h
> +#if QT_VERSION >= 0x060000
Keep only Qt6

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/CustomElements.cpp
> +		const auto istart  = toPlainText().lastIndexOf(QLatin1Char(' '), iend - 1) + 1;
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/GlobalShortcut.cpp
> +#if QT_VERSION >= 0x060000
Keep only Qt6

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/GlobalShortcut.cpp
> +#if QT_VERSION >= 0x060000
Keep only Qt6

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/GlobalShortcut.cpp
> +#if QT_VERSION >= 0x060000
Keep only Qt6

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/GlobalShortcut.cpp
> +				auto idx = qlButtonList.indexOf(button);
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/GlobalShortcut.cpp
> +	const auto idx = qlButtonList.indexOf(button);
Invalid use of `auto`

2024-07-21 05:51 UTC, Krzmbrzl commented on src/mumble/GlobalShortcut_win.cpp
> +#if QT_VERSION < 0x060000
Not needed if we fully switch

2024-07-21 13:23 UTC, davidebeatrici commented
I would like to keep support for Qt 5 at least until the next stable release, but don't want to write a preprocessor block for every `qsizetype` (`int64_t`) vs `int` instance.

I followed [Qt's recommendation](https://doc.qt.io/qt-6/qtcore-changes-qt6.html#api-changes):

> **Note:** If you want to build against both Qt 5 and Qt 6, the auto keyword is a good solution to cover signature differences between the versions.

2024-07-21 15:01 UTC, Krzmbrzl commented
Why do you want to keep Qt5 support? It is EOL already and Qt6 has been around for so long as to be available on all platforms that we want to support (afaik) 🤔

2024-07-21 15:55 UTC, davidebeatrici commented
Right:

https://www.qt.io/blog/qt-5.15-extended-support-for-subscription-license-holders

![](https://github.com/user-attachments/assets/ab29c10c-dba6-40ad-80bd-39e36c25e9ed)

In that case we have to prepare a Qt 6 vcpkg environment.

2024-07-21 16:02 UTC, Krzmbrzl commented
> In that case we have to prepare a Qt 6 vcpkg environment.

Yep

Coming back to the C++17 requirement though: how did you manage it so that nothing breaks? 🤔

2024-07-21 16:44 UTC, davidebeatrici commented
Well, there is one thing "broken": we use the `<codecvt>` header to convert between UTF-8 and UTF-16 and it was [deprecated in C++17](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0618r0.html), resulting in a warning.

Unfortunately there is no standard replacement, we'll have to rely on something like https://github.com/nemtrif/utfcpp.

As for ZeroC Ice: the headers that make use of `std::binary_function` and `std::unary_function` are patched in our fork (which we use in our vcpkg port):

https://github.com/mumble-voip/ice/commit/bc7eb3edf56a5023bdd0b320fd5f0b8ba785726a
https://github.com/mumble-voip/ice/commit/e1e88d8aa16c18a2d12b7d6d28e51f2f20d016a2

Upstream seems to have fixed the issue in v3.7.7: https://github.com/zeroc-ice/ice/commit/bc2762ed4c196ff500ad49bb9e5039e826762045

In conclusion: before merging this PR we should build with Qt 6 to make sure that there are no issues on any platforms.

2024-07-22 00:41 UTC, davidebeatrici commented
#6517

2024-07-23 02:01 UTC, davidebeatrici commented
```
E: Unable to locate package qt6-svg-dev
```

The name was `libqt6svg6-dev` before...

2024-07-23 02:02 UTC, davidebeatrici commented on src/mumble/PluginUpdater.h
> -
I added this change by mistake, it's supposed to fix a separate issue:

```c++
src/mumble/PluginUpdater.cpp:49:18: error: no matching constructor for initialization of 'UpdateEntry'
   49 |                                         UpdateEntry entry = { plugin->getID(), updateURL, updateURL.fileName(), 0 };
      |                                                     ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/mumble/PluginUpdater.h:30:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 4 were provided
   30 | struct UpdateEntry {
      |        ^~~~~~~~~~~
src/mumble/PluginUpdater.h:30:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 4 were provided
   30 | struct UpdateEntry {
      |        ^~~~~~~~~~~
src/mumble/PluginUpdater.h:31:2: note: candidate constructor not viable: requires 0 arguments, but 4 were provided
   31 |         UpdateEntry() = default;
      |         ^
```

2024-08-19 02:49 UTC, davidebeatrici commented
> ```
> E: Unable to locate package qt6-svg-dev
> ```
> 
> The name was `libqt6svg6-dev` before...

Despite `libqt6svg6-dev` being installed just fine, CMake is unable to find Qt's "Svg" component.

The package seemingly contains the required files, which leads me to think something is broken.

Unfortunately we cannot switch to Ubuntu 24.04 in Azure Pipelines because not publicly available yet: https://github.com/actions/runner-images/issues/9848#issuecomment-2264986555

2024-08-19 22:28 UTC, davidebeatrici commented
I ended up adding 24.04's repository and installing the Qt packages from there.

2024-08-20 18:27 UTC, Krzmbrzl commented
We can't exclusively use 24.04 though. At least we have to also have a CI for 22.04

2024-08-20 22:28 UTC, davidebeatrici commented
The base system is still 22.04, but I can see why we should test the Qt packages that are normally provided with it.

Unfortunately we have no choice other than reporting the bug upstream and hoping for a quick fix.

2024-08-21 05:06 UTC, Krzmbrzl commented
Yeah, we should report it. However, until this is fixed I think we should just wait with merging this PR. At least for a couple of weeks to see what the maintainers will do with the reported issue. 👀

2024-08-21 22:50 UTC, davidebeatrici commented
I created a VM with a minimal Ubuntu 22.04 installation and quickly found out what the issue was: missing `libgl-dev`.

Our build log actually gave us a hint, but I missed it as I focused on the specific component (`Svg`). Turns out the `find_pkg()` error is inaccurate: NONE of the GUI-related components were found; or rather, they were ignored due to the missing dependency. 

```
-- Could NOT find OpenGL (missing: OPENGL_INCLUDE_DIR) 
CMake Error at cmake/pkg-utils.cmake:87 (message):
  Qt6 component not found: Svg
Call Stack (most recent call first):
  src/mumble/CMakeLists.txt:76 (find_pkg)
```

A minimal CMake project with the standard `find_package()` call reveals a more accurate log:

```
-- Could NOT find OpenGL (missing: OPENGL_INCLUDE_DIR) 
-- Could NOT find WrapOpenGL (missing: WrapOpenGL_FOUND) 
CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake:219 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt6Gui/Qt6GuiConfig.cmake

  but it set Qt6Gui_FOUND to FALSE so package "Qt6Gui" is considered to be
  NOT FOUND.  Reason given by package:

  Qt6Gui could not be found because dependency WrapOpenGL could not be found.

Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)


-- Could NOT find OpenGL (missing: OPENGL_INCLUDE_DIR) 
-- Could NOT find WrapOpenGL (missing: WrapOpenGL_FOUND) 
CMake Warning at /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt6Gui/Qt6GuiConfig.cmake

  but it set Qt6Gui_FOUND to FALSE so package "Qt6Gui" is considered to be
  NOT FOUND.  Reason given by package:

  Qt6Gui could not be found because dependency WrapOpenGL could not be found.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Qt6/QtPublicDependencyHelpers.cmake:14 (find_dependency)
  /usr/lib/x86_64-linux-gnu/cmake/Qt6Svg/Qt6SvgDependencies.cmake:96 (_qt_internal_find_dependencies)
  /usr/lib/x86_64-linux-gnu/cmake/Qt6Svg/Qt6SvgConfig.cmake:50 (include)
  /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake:219 (find_package)
  CMakeLists.txt:5 (find_package)


CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake:219 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt6Svg/Qt6SvgConfig.cmake

  but it set Qt6Svg_FOUND to FALSE so package "Qt6Svg" is considered to be
  NOT FOUND.  Reason given by package:

  Qt6Svg could not be found because dependency Qt6Gui could not be found.

Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)


-- Could NOT find OpenGL (missing: OPENGL_INCLUDE_DIR) 
-- Could NOT find WrapOpenGL (missing: WrapOpenGL_FOUND) 
CMake Warning at /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt6Gui/Qt6GuiConfig.cmake

  but it set Qt6Gui_FOUND to FALSE so package "Qt6Gui" is considered to be
  NOT FOUND.  Reason given by package:

  Qt6Gui could not be found because dependency WrapOpenGL could not be found.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Qt6/QtPublicDependencyHelpers.cmake:14 (find_dependency)
  /usr/lib/x86_64-linux-gnu/cmake/Qt6Widgets/Qt6WidgetsDependencies.cmake:96 (_qt_internal_find_dependencies)
  /usr/lib/x86_64-linux-gnu/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake:50 (include)
  /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake:219 (find_package)
  CMakeLists.txt:5 (find_package)


CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake:219 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake

  but it set Qt6Widgets_FOUND to FALSE so package "Qt6Widgets" is considered
  to be NOT FOUND.  Reason given by package:

  Qt6Widgets could not be found because dependency Qt6Gui could not be found.

Call Stack (most recent call first):
  CMakeLists.txt:5 (find_package)


CMake Error at CMakeLists.txt:5 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt component "Gui".

  Expected Config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt6Gui/Qt6GuiConfig.cmake" exists

  Failed to find Qt component "Svg".

  Expected Config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt6Svg/Qt6SvgConfig.cmake" exists

  Failed to find Qt component "Widgets".

  Expected Config file at
  "/usr/lib/x86_64-linux-gnu/cmake/Qt6Widgets/Qt6WidgetsConfig.cmake" exists
```

Please note that `libgl-dev` is pulled in automatically with the packages from Ubuntu 24.04, meaning that it's effectively a bug that should be reported.

2024-09-17 00:30 UTC, davidebeatrici commented
Formatted with clang-format 10, in order for CI to succeed.

2024-09-19 03:19 UTC, merged

2024-09-20 13:45 UTC, botanegg commented
Try it on archlinux from aur

Seems like it laggy on first time Settings window was opened

2024-09-20 14:24 UTC, davidebeatrici commented
It feels sluggish when you open the Settings window, but only the first time?

2024-09-27 16:26 UTC, botanegg commented
Found it
At the time I open the Settings window it writes to console next log
```
<W>2024-09-27 23:23:08.481   OpenType support missing for "Ubuntu", script 11
<W>2024-09-27 23:23:08.484   OpenType support missing for "Droid Sans", script 11
<W>2024-09-27 23:23:08.484   OpenType support missing for "DejaVu Sans", script 11

..... <removed more than 3000 lines> ...

<W>2024-09-27 23:23:09.948   OpenType support missing for "Input Mono", script 17
<W>2024-09-27 23:23:09.948   OpenType support missing for "Input Serif", script 17
```

2024-09-27 16:30 UTC, Hartmnt commented
Probably related #4927 and maybe even #5922

2024-09-27 16:32 UTC, botanegg commented
Will recheck on latest release with qt5 (not on master)

2024-09-27 16:35 UTC, botanegg commented
Its OK with Mumble (1.5.634) with Qt  5.15.15

only 1 line in console log
```
<W>2024-09-27 23:34:10.102   OpenType support missing for "Droid Sans", script 11
```

2024-09-27 16:37 UTC, Hartmnt commented
Yea, I think this will be a very hard to track race condition kind of bug. Depending on exact version and system configuration and stuff...

2024-09-27 19:04 UTC, botanegg commented
Fonts scan triggered by

https://github.com/mumble-voip/mumble/blob/c04377960cd70b5a0ee028622d576d34c2764d22/src/mumble/ConfigDialog.cpp#L103

for `LookConfig`

2024-09-28 12:05 UTC, Krzmbrzl commented
To me this kinda looks like a Qt issue because afaict we are not doing any explicit font manipulation kn our end 👀

2024-09-28 12:14 UTC, Hartmnt commented
> To me this kinda looks like a Qt issue because afaict we are not doing any explicit font manipulation kn our end 👀

From what I have read so far, this is a combination of our stylesheet usage and the inability of Qt to properly maintain their stylesheet support. Trying to fix this will likely mean wrestling with Qt for like two weeks again. Additionally, one needs to reliably recreate this bug, which I have not managed to do so far

2024-10-01 05:06 UTC, Guanran928 commented
Hi, are there any plans for updating the documentation?
https://github.com/mumble-voip/mumble/blob/dfa59b1cda3332b96830871a2648663255a3fb7d/docs/dev/build-instructions/build_static.md?plain=1#L45-L49

2024-10-01 20:39 UTC, Krzmbrzl commented
It's (kinda) done via #6588

2025-06-30 19:12 UTC, andreasstieger commented
Are you converging on a release with Qt6? Distribution wants to move away from Qt5, and we would prefer upstream releases over a downstream backport of this.

2025-06-30 19:19 UTC, Hartmnt commented
> Are you converging on a release with Qt6? Distribution wants to move away from Qt5, and we would prefer upstream releases over a downstream backport of this.

Yes, we would like to release the Mumble 1.6 series preferably this year. There will be one ore more release candidates though, similar to the 1.5 series.

That being said, we are currently testing a new bug-fix release for the 1.5 series and those releases might keep coming until the first 1.6 stable release is out. However, official 1.5.x releases will stay on Qt5 for sure.

2025-08-28 21:37 UTC, a17r commented
### Qt5 is now declared deprecated in Gentoo

The final Qt5 release happened on 2025-05-19, which means a) we will not get it until 2026-06-19, b) any bugs discovered since last May will not be fixed and c) no bugs since 2020-12-08 that haven't also been affecting Qt6 were fixed at all.

*At least* Gentoo, Alpine and Ubuntu are entertaining Qt5 porting trackers by now, for Gentoo, Qt5 revdep cleanups are in full swing already.
https://bugs.gentoo.org/show_bug.cgi?id=qt5-removal
https://gitlab.alpinelinux.org/alpine/aports/-/issues/17114
https://ubuntu-archive-team.ubuntu.com/transitions/html/qt5-removal.html