Registered the AudioOutputBuffer as qRegisterMetaType
mumble-voip/mumble pull request #6571
Opened 2024-09-27 22:36 UTC by jaggzh

### Checks

- [ x] My commits follow the [commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md)

### Comments:
I used ChatGPT's help, feeding it the error, explanation, then some greps (with -A1 -B1 context)...
...then, based on what it said, I gave it a chopped down version of main.cpp so it could say where to put the registration (before initializing sound, but it "optimized" that possibly higher than needed -- to some lines further above. I put it in the place cgpt suggested).

2024-09-27 23:21 UTC, Hartmnt requested changes
If you look at other occurrences of ``qRegisterMetaType`` https://github.com/search?q=repo%3Amumble-voip%2Fmumble%20qRegisterMetaType&type=code you can see that those mostly happen in the classes where the connections are being used. So I guess it would make sense to move your call of ``qRegisterMetaType`` in the constructor of ``AudioOutput.cpp` or something

Also please make sure your commit message follows our commit guidelines, otherwise the CI will not pass.  The ChatGPT comment for the single line code change is also probably not needed.

2024-09-28 10:59 UTC, Hartmnt requested changes
I assume you have checked if this still fixes the issue, right? Because you added the line to the ``AudioOutputRegistrar`` constructor instead of the ``AudioOutput`` constructor :smile:
If both works functionally, I am more leaning towards putting it in the ``AudioOutput`` constructor.

The commit message you wrote in the description here on GitHub is fine, but you need to use it as your actual commit message. For that you will need to squash your commits and reword the message. See this for more information: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

2024-09-28 11:02 UTC, Hartmnt commented
In addition to that you did not remove the changes you made to ``main.cpp``. So please make sure your branch only contains relevant changes.

2024-09-28 14:48 UTC, Krzmbrzl requested changes

2024-09-28 14:48 UTC, Krzmbrzl commented on src/mumble/main.cpp
> +
Please also get rid of this changed line in your commit

2024-09-28 14:52 UTC, Hartmnt commented
@Krzmbrzl Would you put this in the constructor of ``AudioOutputRegistrar`` or ``AudioOutput``?

2024-09-28 14:56 UTC, Krzmbrzl commented
I guess technically putting it into the `AudioOutput` constructor makes this execute multiple times (once for every created audio output Backend). Bot sure right now whether that would also be the case with the registrar. 

On the other hand, this does no harm and having the call as close as possible to where it is needed makes semantic sense, I guess. 

In the end I don't have a real preference 🤔

2024-09-28 19:00 UTC, Hartmnt approved these changes
Compiled and tested. Seems to fix the bug.

2024-09-29 08:07 UTC, Krzmbrzl approved these changes

2024-09-29 08:07 UTC, Krzmbrzl approved these changes

2024-09-29 10:30 UTC, merged

2024-09-29 10:31 UTC, Hartmnt commented
@jaggzh Thank you very much for fixing this!