FEAT(client): Control + mouse wheel scroll to adjust local volume in TalkingUI
mumble-voip/mumble pull request #6629
Opened 2024-11-12 23:07 UTC by davidebeatrici

This new feature allows to change the local volume adjustment for the selected user by scrolling the mouse wheel up (increase) or down (decrease) while Control is pressed.

2024-11-15 21:51 UTC, Hartmnt commented
I will look at this in detail after the next 1.5.x release

2024-12-22 15:21 UTC, Hartmnt commented on src/mumble/TalkingUI.cpp
> +	user->setLocalVolumeAdjustment(VolumeAdjustment::toFactor(volAdjustment));
This does set the new local volume temporarily, but it is not retained. You can test this by adjusting the volume using your method and then changing client state of the user you adjusted (e.g. deafen and immediately undeafen) 

To retain the changes we need to add:

```
Global::get().db->setUserLocalVolume(user->qsHash, user->getLocalVolumeAdjustments());
```

2024-12-22 15:21 UTC, Hartmnt commented on src/mumble/TalkingUI.cpp
> +	ClientUser *user = Global::get().mw->pmModel->getSelectedUser();
"Weird" things happen, if you enable to always show your local user (or channel listeners) and use this scroll event. Mainly, it changes the local volume of yourself which has currently no effect IIRC, but can not be changed back using the "self" context menu.

Unless we plan to use self-local-volume-adjustment for something, I think you should add a check that we are not able to change the local volume of ourselves.

2024-12-22 15:21 UTC, Hartmnt commented on src/mumble/TalkingUI.cpp
> +void TalkingUI::wheelEvent(QWheelEvent *event) {
This brings me to my next consideration: Why are we only allowing this in the Talking UI? It feels like the main user list could also profit from this. Maybe I am missing something you already considered?

2025-01-20 23:31 UTC, davidebeatrici commented on src/mumble/TalkingUI.cpp
> +void TalkingUI::wheelEvent(QWheelEvent *event) {
I wanted to do that in a separate pull request, but it would probably make more sense to just add a commit here.

The question now is: do we want to keep separate options for the main user list and the Talking UI or a single one for both?

2025-03-02 14:40 UTC, Hartmnt commented on src/mumble/TalkingUI.cpp
> +void TalkingUI::wheelEvent(QWheelEvent *event) {
Ok, I thought about this a little bit and I would say it is probably enough to have a single option for this behavior. I think a user would expect this to happen for all instances of user representations, if enabled.

2025-04-05 16:14 UTC, Krzmbrzl commented on src/mumble/TalkingUI.cpp
> +void TalkingUI::wheelEvent(QWheelEvent *event) {
I agree that a single combined option is probably desirable

2025-04-08 06:40 UTC, davidebeatrici commented on src/mumble/LookConfig.ui
> +       <widget class="QCheckBox" name="qcbCtrlScrollLocalVolAdj">
Found a solution: https://stackoverflow.com/questions/65463217/qt-ui-file-xml-order-qgridlayout-row-order-leads-to-large-commit-differences

2025-04-09 15:15 UTC, davidebeatrici commented on src/mumble/LookConfig.ui
> +       <widget class="QCheckBox" name="qcbCtrlScrollLocalVolAdj">
Oh sorry. The diff problem had to eventually be fixed as well anyway.

The tab order editing process is actually documented on Qt's website: https://doc.qt.io/qt-6/designer-tab-order.html

2025-04-16 18:58 UTC, Hartmnt approved these changes, later dismissed
Compiled again. Seems to work fine now. Did not find accessibility problems.

What is the PR policy with sorting the UI files going forward?

2025-04-17 05:03 UTC, davidebeatrici commented
Excellent question. I believe we should add the script to the repository and introduce a CI check.

2026-09-13 07:42 UTC, Krzmbrzl commented
@davidebeatrici what's your plan with this PR?

2026-09-14 02:19 UTC, davidebeatrici commented
@Krzmbrzl I removed the commit(s) that refactored the `.ui` files, we should do it in a separate pull request that also adds an enforcement check to CI as I suggested last year (time flies...).

In order to keep a sane diff I edited `LookConfig.ui` manually.

2026-09-14 08:07 UTC, Krzmbrzl requested changes

2026-09-14 08:07 UTC, Krzmbrzl commented on src/mumble/Settings.h
> +	bool bCtrlScrollLocalVolAdj          = true;
Don't use type-prefixing in new code

2026-09-14 08:07 UTC, Krzmbrzl commented on src/mumble/UserView.cpp
> +void UserView::wheelEvent(QWheelEvent *event) {
It seems like most of the code can (and probably should) be shared between the `TalkingUI` impl and this one.

2026-09-14 08:07 UTC, Krzmbrzl commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
Should just return `int`. There is no inherent reason why this should be limited to `int8_t`

2026-09-14 18:26 UTC, davidebeatrici commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
By explicitly returning the smallest datatype that can hold the value you ensure two things:

1. No extra memory is needlessly used, `int` under common circumstances is 4 bytes.
2. Returning a larger datatype would result in a warning when assigning the value to a variable with a smaller datatype.

In this case both functions are `constexpr` and we call them to set the values through functions that take an `int`, meaning that it wouldn't make any difference whatsoever.

But, just in case the code will be used somewhere else, I used the correct datatype (which can go down to -128 and up to 127 anyway).

2026-09-14 21:12 UTC, davidebeatrici commented on src/mumble/UserView.cpp
> +void UserView::wheelEvent(QWheelEvent *event) {
Done.

2026-09-14 21:12 UTC, davidebeatrici commented on src/mumble/Settings.h
> +	bool bCtrlScrollLocalVolAdj          = true;
Fixed.

2026-09-15 08:10 UTC, Krzmbrzl commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
1) is unnecessary because it is absolutely not measurable under any real-life circumstance and - as you have noted yourself - incorrect due to the way we use the value.

2) is not an issue if one was to just use `int` at the calling site as well :)

> But, just in case the code will be used somewhere else, I used the correct datatype (which can go down to -128 and up to 127 anyway).

"correct" is very subjective here. There doesn't exist a type that encompasses the currently valid range exactly and therefore inferring the valid values from the datatype is not possible anyway. Hence, I always recommend against micro-engineering interfaces and just use the commonly used type (in this case a signed integer, aka: `int`). Anything else will make people stop and wonder why this specific type was used when reading the code. In this case, I would argue there are no actually useful conclusions to be reached from the type.

2026-09-15 08:41 UTC, Krzmbrzl commented on src/mumble/Settings.h
> +	bool m_ctrlScrollLocalVolAdj         = true;
I think for settings we never used the `m_` prefix (it's a globally visible variable). We tend to just use the name without any prefix.

2026-09-15 08:41 UTC, Krzmbrzl approved these changes, later dismissed

2026-09-16 03:57 UTC, davidebeatrici commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
In this case, especially with the function being `constexpr`, I would just use `auto` and let the compiler decide the datatype then.

2026-09-16 03:58 UTC, davidebeatrici commented on src/mumble/Settings.h
> +	bool m_ctrlScrollLocalVolAdj         = true;
Right, we treat it as a struct and don't have getters/setters.

2026-09-16 05:31 UTC, merged

2026-09-16 05:53 UTC, Krzmbrzl commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
It'll be `int` so we could just use that directly :D

2026-09-16 06:06 UTC, davidebeatrici commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
Yeah, but I like to let the compiler be the judge since it's aware of the value and that it cannot change; `constexpr` in this case could be considered a modern replacement for a preprocessor definition. :)

2026-09-16 08:19 UTC, Krzmbrzl commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
It doesn't have a real choice. An integer literal is mandated to be an `int` unless it is larger than representable by an `int` afaik

2026-09-16 08:30 UTC, davidebeatrici commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
Yeah, that's how I've always seen compilers behave, but the use of `auto` in this case kind of points out that we only care about the value itself and not the returned datatype.

Generally speaking, I evaluate the circumstances before choosing the integer size; for example, for a network port I always choose `uint16_t` as the range is 0-65535.

Of course it's not going to make a noticeable difference in terms of memory usage when it's a single variable, but there's a far higher chance when it's a class/struct member due to alignment and the fact there can theoretically be infinite instances/objects.

2026-09-16 08:42 UTC, Krzmbrzl commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
Imo code remains more readable if we just stick to standard integer types unless there is an actual, measurable reason for not doing so. That'll increase the signal-to-noise ratio when reading the code.

2026-09-16 09:17 UTC, davidebeatrici commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
It's true that, unfortunately in my opinion, the compiler only knows about `int`, `short`, `long` and the such, but fixed-width integers have been part of the standard library for a long while. Also, keep in mind third-party definitions such as WinAPI's have always existed.

I believe the code appearing more readable when using the compiler's built-in datatypes is just because most of the code around stick with them.

2026-09-16 09:57 UTC, Krzmbrzl commented on src/mumble/VolumeSliderWidgetAction.h
> +	static constexpr std::int8_t max() { return 30; }
I know that they exist but I think they are only useful under very specific circumstances and everywhere else one should just stick to the standard types.

>I believe the code appearing more readable when using the compiler's built-in datatypes is just because most of the code around stick with them.

Maybe. But that doesn't change the facts. Also, I think part of the readability is also due to the amount of information encoded in the type. If you use `int` you only say "I use a signed integer type of reasonable but undetermined size" whereas if you use e.g. `std::int32_t` you say "I used a signed integer that is _exactly_ 32 bits wide" which always incurs the question "why is it being exactly of this size important?" which is extra mental load that might be warranted but only when this question has a clear answer.